version: '3.8'

services:
  forward-proxy:
    build: .
    ports:
      - "7770:7770"
    networks:
      - default
      - pangolin_net
    volumes:
      - ./users.db:/app/users.db
    env_file:
      - .env
    restart: unless-stopped
networks:
  default:
  pangolin_net:
    external: true
